name: Battle Bottles CI/CD

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

defaults:
  run:
    working-directory: ./battlebottles

jobs:
  test_and_analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Create firebase_options.dart
        env:
          FIREBASE_DATA: ${{ secrets.FIREBASE_OPTIONS_BASE64 }}
        run: |
          echo "$FIREBASE_DATA" | base64 --decode > lib/firebase_options.dart

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze code
        run: flutter analyze

      - name: Run tests
        run: flutter test

  deploy_web:
    needs: test_and_analyze
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Create firebase_options.dart
        env:
          FIREBASE_DATA: ${{ secrets.FIREBASE_OPTIONS_BASE64 }}
        run: |
          echo "$FIREBASE_DATA" | base64 --decode > lib/firebase_options.dart

      - name: Install dependencies
        run: flutter pub get

      - name: Build Web App
        run: flutter build web --release --wasm

      - name: Deploy to Firebase Hosting
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
          entryPoint: ./battlebottles
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

  build_android:
    needs: test_and_analyze
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Create firebase_options.dart
        env:
          FIREBASE_DATA: ${{ secrets.FIREBASE_OPTIONS_BASE64 }}
        run: |
          echo "$FIREBASE_DATA" | base64 --decode > lib/firebase_options.dart

      - name: Create google-services.json
        env:
          GOOGLE_SERVICES_DATA: ${{ secrets.GOOGLE_SERVICES_JSON_BASE64 }}
        run: |
          echo "$GOOGLE_SERVICES_DATA" | base64 --decode > android/app/google-services.json

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: battle-bottles-release
          path: battlebottles/build/app/outputs/flutter-apk/app-release.apk